[[financial_services.keymanager.application.type.attributes]]
name="jwks_uri"
label="JWKS URI"
type="input"
tooltip="Endpoint serving the public keys of the application, used to validate private_key_jwt client assertions and signed request objects"
values=""
default=""
required="true"
mask="false"
multiple="false"
priority="1"
hidden="false"

[[financial_services.keymanager.application.type.attributes]]
name="regulatory"
default="true"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="token_endpoint_auth_method"
default="private_key_jwt"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="token_endpoint_auth_signing_alg"
default="PS256"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="request_object_signing_alg"
default="PS256"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="id_token_signed_response_alg"
default="PS256"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="require_signed_request_object"
default="true"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="require_pushed_authorization_requests"
default="true"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="tls_client_certificate_bound_access_tokens"
default="true"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="ext_pkce_mandatory"
default="true"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="ext_pkce_support_plain"
default="false"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="ext_public_client"
default="false"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="token_endpoint_allow_reuse_pvt_key_jwt"
default="false"
hidden="true"

[[financial_services.keymanager.application.type.attributes]]
name="ext_allowed_audience"
default="organization"
hidden="true"